name: police_info_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_cli: ^1.6.0
  flutter: 
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3+3
  age: ^0.0.1
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.3
  qr_flutter: ^4.0.0
#  flutter_cupertino_date_picker: ^1.0.26+2
  intl: ^0.17.0
  path_provider: ^2.0.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/police.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

